/**
 * @jbcom/strata API
 *
 * Strata organizes its API into six domains based on how you'll use them:
 *
 * ## Domains
 *
 * ### World Building
 * Terrain, water, vegetation, sky, and atmosphere - the foundation of your 3D environment.
 *
 * ### Entities & Simulation
 * Characters, physics, animation, and AI - dynamic objects that move and interact.
 *
 * ### Effects & Atmosphere
 * Particles, weather, decals, lighting effects - visual polish that brings scenes to life.
 *
 * ### Player Experience
 * Cameras, input, audio, and UI - how players see, control, hear, and understand your game.
 *
 * ### Game Systems
 * State management, save/load, checkpoints - the infrastructure powering your game.
 *
 * ### Compositional Objects
 * Materials, skeletons, props, and creatures - define complex objects declaratively.
 *
 * ### Rendering Pipeline
 * Shaders, post-processing, materials - low-level graphics for advanced customization.
 *
 * ## Quick Start
 *
 * ```tsx
 * // Import from specific domains
 * import { Terrain, Water, ProceduralSky } from '@jbcom/strata/api/world';
 * import { CharacterController, Ragdoll } from '@jbcom/strata/api/entities';
 * import { ParticleEmitter, Rain } from '@jbcom/strata/api/effects';
 *
 * // Or import everything
 * import * as Strata from '@jbcom/strata';
 * ```
 *
 * @module API
 * @category Overview
 */

export { createActionGame, createPlatformerGame, createPuzzleGame, createRPGGame, createRacingGame, createSandboxGame } from "../game/game-presets";
export type { ActionGameOptions, ActionState, DeepPartial, PlatformerGameOptions, PuzzleGameOptions, PuzzleState, RPGGameOptions, RPGState, RacingGameOptions, RacingState, SandboxGameOptions, SandboxState } from "../game/game-presets";
export { createAnnouncementScene, createAnnouncementSceneShell, createClearProfileSceneShellAction, createDeleteSaveSceneShellAction, createDismissSceneShellAction, createLoadActiveProfileSceneShellAction, createLoadGameSceneShellAction, createLoadLatestProfileSceneShellAction, createLoadSceneShellAction, createMenuScene, createMenuSceneShell, createOpenActiveProfileArchiveSceneShellAction, createPauseSceneShellAction, createPopModeSceneShellAction, createPopSceneShellAction, createPushModeSceneShellAction, createPushSceneShellAction, createReplaceModeSceneShellAction, createResumeSceneShellAction, createSaveGameSceneShellAction, createSaveProfilesScene, createSaveProfilesSceneShell, createSaveScene, createSaveSceneShell, createSessionScene, createSessionSceneShell, createTitleScene, createTitleSceneShell, createTogglePauseSceneShellAction } from "../game/scene-shell-presets";
export { createSceneShellFlow } from "../game/shell-flow-presets";
export type { CreateSceneShellFlowOptions, SceneShellFlowActionLabels, SceneShellFlowDefaults, SceneShellFlowMenuOptions, SceneShellFlowResult, SceneShellFlowSaveProfile, SceneShellFlowSaveProfileSelectorOptions, SceneShellFlowSaveSlot, SceneShellFlowSavesOptions, SceneShellFlowSessionOptions, SceneShellFlowSettingsOptions, SceneShellFlowTitleOptions, ShellFlowLoadLatestProfileActionInput, ShellFlowPersistenceActionInput, ShellFlowScaffoldInput, ShellFlowSceneLoadActionInput, ShellFlowTogglePauseActionInput } from "../game/shell-flow-presets";
export { COVERINGS, CREATURES, MATERIALS, PROPS, SKELETONS, createAvianSkeleton, createBipedSkeleton, createCreature, createCreatureAnimationGraph, createCreatureIKPosePlan, createCreatureIKRigPlan, createFurMaterial, createMaterialProceduralBakeArtifacts, createMaterialProceduralBakeBasisUniversalKtx2Encoder, createMaterialProceduralBakeBrowserImageEncoder, createMaterialProceduralBakeExportPlan, createMaterialProceduralBakePlan, createMaterialProceduralPlan, createMaterialTrait, createMaterialVariant, createMaterialVariants, createMetalMaterial, createOrganicMaterial, createProp, createQuadrupedSkeleton, createSerpentineSkeleton, createShellMaterial, createVolumetricMaterial, createWoodMaterial, encodeMaterialProceduralBakeExportPlan, encodeMaterialProceduralBakeImagePng, encodeMaterialProceduralBakeRasterPng, inferMaterialTraits, rasterizeMaterialProceduralBakePlan, resolveCreatureComposition, resolvePropComposition } from "./compose";
export type { BoneDefinition, CoveringDefinition, CoveringRegion, CreateCreatureInput, CreatePropInput, CreatureComposition, CreatureDefinition, CreatureRuntimeAnimationBinding, CreatureRuntimeAnimationBlendGroup, CreatureRuntimeAnimationGraph, CreatureRuntimeAnimationGraphOptions, CreatureRuntimeAnimationGraphState, CreatureRuntimeAnimationGraphTransition, CreatureRuntimeAnimationTransitionMode, CreatureRuntimeAssembly, CreatureRuntimeBone, CreatureRuntimeIKChainBonePlan, CreatureRuntimeIKChainPlan, CreatureRuntimeIKChainPosePlan, CreatureRuntimeIKChainStatus, CreatureRuntimeIKPose, CreatureRuntimeIKPosePlan, CreatureRuntimeIKPosePlanOptions, CreatureRuntimeIKPoseTransform, CreatureRuntimeIKPoseVector, CreatureRuntimeIKRigCoverage, CreatureRuntimeIKRigPlan, CreatureRuntimeIKSolverKind, CreatureRuntimeIKTarget, CreatureRuntimeIKTargetMap, CreatureRuntimeSpawnProfile, DropItem, DropTable, IKChainDefinition, MarkingDefinition, MaterialDefinition, MaterialPhysics, MaterialProceduralBakeArtifacts, MaterialProceduralBakeBasisUniversalEncoder, MaterialProceduralBakeBasisUniversalKtx2EncoderOptions, MaterialProceduralBakeBrowserImageEncoderOptions, MaterialProceduralBakeCanvas2DContextLike, MaterialProceduralBakeCanvasLike, MaterialProceduralBakeColorSpace, MaterialProceduralBakeEncodedImage, MaterialProceduralBakeExportEncoder, MaterialProceduralBakeExportEncoderFn, MaterialProceduralBakeExportEncoderOptions, MaterialProceduralBakeExportExecutionOptions, MaterialProceduralBakeExportManifest, MaterialProceduralBakeExportMimeType, MaterialProceduralBakeExportOptions, MaterialProceduralBakeExportPlan, MaterialProceduralBakeExportRequest, MaterialProceduralBakeExportResult, MaterialProceduralBakeFormat, MaterialProceduralBakeImageDataLike, MaterialProceduralBakeManifest, MaterialProceduralBakeMap, MaterialProceduralBakePlan, MaterialProceduralBakePlanOptions, MaterialProceduralBakeRaster, MaterialProceduralBakeRasterImage, MaterialProceduralColor, MaterialProceduralLayer, MaterialProceduralPlan, MaterialProceduralPlanOptions, MaterialProceduralUniform, MaterialTrait, MaterialTraitChannel, MaterialTraitInferenceOptions, MaterialTraitOptions, MaterialTraitType, MaterialType, MaterialVariantOptions, MaterialVariantSetOptions, OrganicProperties, PatternDefinition, PropComponent, PropComposition, PropDefinition, PropRuntimeAssembly, PropRuntimeNode, RuntimeBounds, RuntimeMaterialSlot, RuntimePhysicsProfile, RuntimeQuaternionTuple, RuntimeVector3Tuple, ShellPattern, ShellProperties, SkeletonDefinition, VolumetricProperties } from "./compose";
export { STATE_PRESETS, createActionState, createGame, createPuzzleState, createRPGState, createRacingState, createSandboxState, createStateFromPreset, getStatePresetDefinition, isBuiltInStatePreset } from "./createGame";
export type { BuiltInStatePreset, PresetGameDefinition, StateForPreset, StatePresetDefinition } from "./createGame";
export { CoreParticleEmitter, CoreWeatherSystem, DecalProjector, LODManager, WindSimulation, applySpriteSheetFrame, batchLODObjects, blendGodRayColors, calculateGodRayIntensityFromAngle, calculateImpostorAngle, calculateLODLevel, calculateScatteringIntensity, calculateScreenSpaceSize, calculateTemperature, calculateVegetationDensity, createBillboardMatrix, createBloodSplatterTexture, createBulletHoleTexture, createDecalTexture, createDitherPattern, createFootprintTexture, createGodRaysMaterial, createImpostorGeometry, createImpostorTexture, createLODLevels, createParticleEmitter, createPointLightSphereGeometry, createScorchMarkTexture, createSpotlightConeGeometry, createSpriteSheetAnimation, createSpriteSheetMaterial, createVegetationLODLevels, createVolumetricPointLightMaterial, createVolumetricSpotlightMaterial, createWaterPuddleTexture, createWeatherSystem, createWindSimulation, generateLODGeometries, getLightScreenPosition, getPrecipitationType, getSpriteSheetUVs, interpolateLODMaterials, shouldUseLOD, simplifyGeometry, sortBillboardsByDepth, updateBillboardRotation, updateImpostorUV, updateSpriteSheetAnimation } from "./effects";
export type { BillboardConfig, DecalInstance, DecalProjectorConfig, EmissionShape, EmitterShapeParams, GodRaysMaterialOptions, ImpostorConfig, LODConfig, LODLevel, LODState, ParticleBehavior, ParticleEmitterConfig, ParticleForces, SimplificationOptions, SpriteAnimationState, SpriteSheetConfig, TemperatureConfig, VegetationLODConfig, VolumetricPointLightMaterialOptions, VolumetricSpotlightMaterialOptions, WeatherStateConfig, WeatherStateCore, WeatherTransition, WeatherType, WindConfig } from "./effects";
export { CCDSolver, CollisionLayer, FABRIKSolver, LookAtController, ProceduralGait, SpringChain, SpringDynamics, TwoBoneIKSolver, applyDrag, calculateBoneRotation, calculateBuoyancyForce, calculateExplosionForce, calculateForce, calculateImpulse, calculateJumpImpulse, calculateLandingVelocity, calculateSlopeAngle, calculateSteeringAngle, calculateSuspensionForce, clampAngle, collisionFilters, createBoneChain, createBoneChainFromLengths, createDefaultBuoyancyConfig, createDefaultCharacterConfig, createDefaultDestructibleConfig, createDefaultPhysicsConfig, createDefaultVehicleConfig, createHumanoidRagdoll, dampedSpring, dampedSpringVector3, generateDebrisVelocity, hermiteInterpolate, isWalkableSlope, projectVelocityOntoGround, sampleCurve } from "./entities";
export type { BoneChain, BoneConstraint, BuoyancyConfig, CharacterControllerConfig, CollisionFilter, DestructibleConfig, GaitConfig, GaitState, IKSolverResult, LookAtConfig, LookAtState, PhysicsConfig, PhysicsMaterial, RagdollBodyPart, RagdollConfig, RagdollJointConfig, SpringConfig, SpringState, VehicleConfig, WheelConfig } from "./entities";
export { CoreCameraShake, DEFAULT_SPATIAL_CONFIG, ENVIRONMENT_PRESETS, FOVTransition, HapticFeedback, Howl, Howler, InputManager, InputStateMachine, SoundManager, SpatialAudio, angleToAxis, axisToAngle, axisToMagnitude, calculateFade, calculateHeadBob, calculateLookAhead, calculateScreenShakeIntensity, clampAxis, clampProgress, createDefaultCrosshair, createDefaultDamageNumber, createDefaultDialog, createDefaultInventory, createDefaultMinimap, createDefaultNameplate, createDefaultNotification, createDefaultProgressBar, createDefaultTooltip, createInputManager, createSoundManager, createSpatialAudio, easeInCubic, easeInOutCubic, evaluateCatmullRom, formatNumber, formatProgressText, getAnchorOffset, getAudioContext, getDamageNumberColor, getNotificationColor, getNotificationIcon, getTextDirection, isAudioContextUnlocked, lerp, lerpVector3, normalizeAxisValue, resumeAudioContext, screenToWorld, setupAutoUnlock, slerp, smoothDamp, smoothDampScalar, smoothDampVector3, suspendAudioContext, unlockAudioContext, worldToScreen } from "./experience";
export type { AudioBus, AudioConfig, AudioFormat, AudioListenerState, AudioMixer, CameraPath, CameraShakeConfig, CrosshairConfig, DamageNumberConfig, DialogChoice, DialogConfig, DialogLine, DistanceModel, DragState, EnvironmentEffectConfig, EnvironmentPreset, FOVTransitionConfig, GamepadState, HapticPattern, InputActionBinding, InputActionMap, InputActionSource, InputAxis, InputEvent, InputManagerConfig, InputManagerSnapshot, InventoryConfig, InventorySlot, MinimapConfig, MinimapMarker, NameplateConfig, NotificationConfig, PointerState, ProgressBarConfig, ScreenPosition, ScreenShakeIntensity, SoundConfig, SpatialConfig, TextDirection, TooltipConfig, UIAnchor } from "./experience";
export { MathChunks, NoiseChunks, ShaderChunks, TEXTURE_PROVIDER_PATTERNS, advancedWaterFragmentShader, advancedWaterVertexShader, apertureToBokehScale, atmosphereFragmentShader, atmosphereShader, atmosphereVertexShader, blendPostProcessingPresets, calculateFocusDistance, calculateFocusDistanceToMesh, clearOptionalPackageCache, clearTextureCache, cloudLayerFragmentShader, cloudLayerVertexShader, createAdvancedWaterUniforms, createAtmosphereUniforms, createCloudLayerUniforms, createCrystalMaterial, createDissolveMaterial, createDustParticlesUniforms, createForcefieldMaterial, createFurUniforms, createGlitchMaterial, createGodRaysUniforms, createGradientMaterial, createHologramMaterial, createInstancingWindUniforms, createOutlineMaterial, createRaymarchingGeometry, createRaymarchingMaterial, createRaymarchingUniforms, createScanlineMaterial, createSimpleTerrainUniforms, createSkyUniforms, createTerrainMaterial, createTerrainUniforms, createToonMaterial, createUnderwaterOverlayUniforms, createUnderwaterUniforms, createVolumetricCloudUniforms, createVolumetricFogMeshUniforms, createVolumetricFogUniforms, createVolumetricPointLightUniforms, createVolumetricSpotlightUniforms, createWaterUniforms, defaultEffectSettings, defaultFurConfig, dofScenarios, dustParticlesFragmentShader, dustParticlesShader, dustParticlesVertexShader, focalLengthToFOV, fovToFocalLength, furFragmentShader, furVertexShader, getOptionalPackagesStatus, getTimeOfDayEffects, godRaysFragmentShader, godRaysVertexShader, instancingWindVertexShader, isOptionalPackageAvailable, loadBiomeTextures, loadOptionalPackage, loadTexture, loadTextureSet, lutConfigs, mergeOptionalExports, noiseSnippet, preloadBiomeTextures, probeOptionalPackage, raymarchingFragmentShader, raymarchingVertexShader, simpleTerrainFragmentShader, simpleTerrainVertexShader, skyFragmentShader, skyVertexShader, terrainFragmentShader, terrainVertexShader, underwaterFragmentShader, underwaterOverlayFragmentShader, underwaterOverlayVertexShader, underwaterShader, underwaterVertexShader, volumetricCloudFragmentShader, volumetricCloudVertexShader, volumetricFogFragmentShader, volumetricFogMeshFragmentShader, volumetricFogMeshVertexShader, volumetricFogShader, volumetricFogVertexShader, volumetricPointLightFragmentShader, volumetricPointLightVertexShader, volumetricSpotlightFragmentShader, volumetricSpotlightVertexShader, waterFragmentShader, waterVertexShader } from "./rendering";
export type { AdvancedWaterUniforms, AtmosphereUniforms, BiomeType, BloomSettings, BrightnessContrastSettings, ChromaticAberrationSettings, CloudLayerUniforms, ColorGradingSettings, ColorRepresentation, CrystalMaterialOptions, DOFSettings, DissolveMaterialOptions, DustParticlesUniforms, FilmGrainSettings, ForcefieldMaterialOptions, FurConfig, FurUniforms, GlitchMaterialOptions, GodRaysUniforms, GradientMaterialOptions, HologramMaterialOptions, IUniforms, InstancingWindUniforms, LUTConfig, NoiseSettings, OptionalPackageStatus, OutlineMaterialOptions, PostProcessingMood, PostProcessingPreset, RaymarchingUniforms, SSAOSettings, ScanlineMaterialOptions, SepiaSettings, SimpleTerrainUniforms, SkyUniforms, StandardTextureType, TerrainTextures, TerrainUniforms, ToneMappingSettings, ToonMaterialOptions, UnderwaterOverlayUniforms, UnderwaterUniforms, UniformValue, Vector2Representation, Vector3Representation, VignetteSettings, VolumetricCloudUniforms, VolumetricFogMeshUniforms, VolumetricFogUniforms, VolumetricPointLightUniforms, VolumetricSpotlightUniforms, WaterUniforms } from "./rendering";
export { calculateChecksum, create, createGameStore, createPersistenceAdapter, createWebPersistenceAdapter, immer, temporal, useStore, verifyChecksum, webPersistenceAdapter } from "./systems";
export type { CheckpointOptions, GameStoreActions, GameStoreState, PersistenceAdapter, SaveData, StateChangeType, StateListener, StoreConfig } from "./systems";
export { adaptCloudColorsForTimeOfDay, calcNormal, calculateWindOffset, createAdvancedWaterMaterial, createCloudLayerGeometry, createCloudLayerMaterial, createDefaultCloudSkyConfig, createGeometryFromMarchingCubes, createInstancedMesh, createSkyGeometry, createSkyMaterial, createUnderwaterOverlayMaterial, createVolumetricCloudGeometry, createVolumetricCloudMaterial, createVolumetricFogMeshMaterial, createWaterGeometry, createWaterMaterial, fbm, fbmNoise2D, generateTerrainChunk, getBiomeAt, getTerrainHeight, marchingCubes, noise3D, opIntersection, opSmoothIntersection, opSmoothSubtraction, opSmoothUnion, opSubtraction, opUnion, sampleCloudDensity, sdBox, sdCapsule, sdCaves, sdCone, sdPlane, sdRock, sdSphere, sdTerrain, sdTorus, warpedFbm } from "./world";
export type { AdvancedWaterMaterialOptions, BiomeData, CloudLayerConfig, CloudMaterialOptions, CloudSkyConfig, InstanceData, MarchingCubesOptions, MarchingCubesResult, TerrainChunk, TimeOfDayStateCore, VolumetricCloudOptions } from "./world";
