export type {
  ControlHints,
  DeviceInfo,
  DeviceProfile,
  DeviceType,
  HapticsOptions,
  InputMapping,
  InputMode,
  InputSnapshot,
  Orientation,
  OrientationOptions,
  PerformanceMode,
  Platform,
  SafeAreaInsets,
  StorageKeysResult,
  StorageOptions,
  StorageResult,
  StrataPlugin,
  TouchOptions,
  Vector2,
} from '@strata-game-library/capacitor';
export {
  DEFAULT_INPUT_MAPPING,
  hello,
  Strata,
  version,
} from '@strata-game-library/capacitor';
