/** Optional Yuka steering and navigation integration. */
export type {
  StateConfig,
  UseAlignmentOptions,
  UseArriveOptions,
  UseCohesionOptions,
  UseEvadeOptions,
  UseFleeOptions,
  UseFollowPathOptions,
  UseInterposeOptions,
  UseObstacleAvoidanceOptions,
  UseOffsetPursuitOptions,
  UsePursueOptions,
  UseSeekOptions,
  UseSeparationOptions,
  UseWanderOptions,
  YukaEntityManagerContextValue,
  YukaEntityManagerProps,
  YukaNavMeshProps,
  YukaNavMeshRef,
  YukaPathProps,
  YukaPathRef,
  YukaStateMachineProps,
  YukaStateMachineRef,
  YukaVehicleProps,
  YukaVehicleRef,
} from '@strata-game-library/yuka';
export {
  createPolygonsFromGeometry,
  syncYukaToThree,
  threeVector3ToYuka,
  useAlignment,
  useArrive,
  useCohesion,
  useEvade,
  useFlee,
  useFollowPath,
  useInterpose,
  useObstacleAvoidance,
  useOffsetPursuit,
  usePursue,
  useSeek,
  useSeparation,
  useWander,
  useYukaContext,
  YUKA,
  YukaEntityManager,
  YukaNavMesh,
  YukaPath,
  YukaStateMachine,
  YukaVehicle,
  yukaVector3ToThree,
} from '@strata-game-library/yuka';
