/**
 * Core Mathematical and Procedural Generation Utilities.
 * @packageDocumentation
 * @module core
 */

export {
  calculateBlendWeights,
  calculateBoneRotation,
  CCDSolver,
  clampAngle,
  createAnimationMachine,
  createBoneChain,
  createBoneChainFromLengths,
  createCombatMachine,
  createLocomotionMachine,
  dampedSpring,
  dampedSpringVector3,
  FABRIKSolver,
  hermiteInterpolate,
  LookAtController,
  ProceduralGait,
  sampleCurve,
  smootherStep,
  smoothStep,
  SpringChain,
  SpringDynamics,
  TwoBoneIKSolver,
} from './animation';
export type {
  AnimationBlendReturn,
  AnimationContext,
  AnimationEvent,
  AnimationMachineConfig,
  AnimationMachineReturn,
  AnimationStateConfig,
  AnimationStateName,
  AnimationTransitionConfig,
  BlendTreeConfig,
  BlendTreeNode,
  BlendWeights,
  BoneChain,
  BoneConstraint,
  GaitConfig,
  GaitState,
  IKSolverResult,
  LookAtConfig,
  LookAtState,
  SpringConfig,
  SpringState,
  UseAnimationBlendOptions,
  UseAnimationMachineOptions,
} from './animation';
export {
  createSoundManager,
  createSpatialAudio,
  DEFAULT_SPATIAL_CONFIG,
  ENVIRONMENT_PRESETS,
  getAudioContext,
  Howl,
  Howler,
  isAudioContextUnlocked,
  resumeAudioContext,
  setupAutoUnlock,
  SoundManager,
  SpatialAudio,
  suspendAudioContext,
  unlockAudioContext,
} from './audio';
export type {
  AudioBus,
  AudioConfig,
  AudioFormat,
  AudioListenerState,
  AudioMixer,
  DistanceModel,
  EnvironmentEffectConfig,
  EnvironmentPreset,
  SoundConfig,
  SpatialConfig,
} from './audio';
export {
  calculateHeadBob,
  calculateLookAhead,
  calculateScreenShakeIntensity,
  CameraShake,
  CameraShakeCore,
  evaluateCatmullRom,
  FOVTransition,
  lerpVector3,
  slerp,
  smoothDampScalar,
  smoothDampVector3,
} from './camera';
export type {
  CameraPath,
  CameraShakeConfig,
  CameraShakeType,
  FOVTransitionConfig,
  ScreenShakeIntensity,
} from './camera';
export {
  adaptCloudColorsForTimeOfDay,
  calculateWindOffset,
  createCloudLayerGeometry,
  createCloudLayerMaterial,
  createDefaultCloudSkyConfig,
  createVolumetricCloudGeometry,
  createVolumetricCloudMaterial,
  fbmNoise2D,
  sampleCloudDensity,
} from './clouds';
export type {
  CloudLayerConfig,
  CloudMaterialOptions,
  CloudSkyConfig,
  DayNightConfig,
  VolumetricCloudOptions,
  WindConfig,
} from './clouds';
// Debug tools (React-dependent) moved to @strata-game-library/r3f
export {
  applySpriteSheetFrame,
  createBillboardMatrix,
  createBloodSplatterTexture,
  createBulletHoleTexture,
  createDecalTexture,
  createFootprintTexture,
  createScorchMarkTexture,
  createSpriteSheetAnimation,
  createSpriteSheetMaterial,
  createWaterPuddleTexture,
  DecalProjector,
  getSpriteSheetUVs,
  sortBillboardsByDepth,
  updateBillboardRotation,
  updateSpriteSheetAnimation,
} from './decals';
export type {
  BillboardConfig,
  DecalInstance,
  DecalProjectorConfig,
  SpriteAnimationState,
  SpriteSheetConfig,
} from './decals';
export {
  addComponent,
  ARCHETYPES,
  combineSystems,
  conditionalSystem,
  countEntities,
  createFromArchetype,
  createSystem,
  createSystemScheduler,
  createWorld,
  findEntityById,
  generateEntityId,
  hasComponents,
  removeComponent,
  resetEntityIdCounter,
  withTiming,
  World,
} from './ecs';
export type {
  Archetype,
  BaseEntity,
  ComponentKeys,
  OptionalComponents,
  QueryResult,
  RequiredComponents,
  StrataWorld,
  SystemConfig,
  SystemFn,
  SystemScheduler,
  WorldConfig,
} from './ecs';
export {
  blendGodRayColors,
  calculateGodRayIntensityFromAngle,
  calculateScatteringIntensity,
  createGodRaysMaterial,
  createPointLightSphereGeometry,
  createSpotlightConeGeometry,
  createVolumetricPointLightMaterial,
  createVolumetricSpotlightMaterial,
  getLightScreenPosition,
} from './godRays';
export type {
  GodRaysMaterialOptions,
  VolumetricPointLightMaterialOptions,
  VolumetricSpotlightMaterialOptions,
} from './godRays';
export {
  angleToAxis,
  axisToAngle,
  axisToMagnitude,
  clampAxis,
  createInputManager,
  HapticFeedback,
  InputManager,
  InputStateMachine,
  normalizeAxisValue,
} from './input';
export type {
  DragState,
  GamepadState,
  HapticPattern,
  InputActionBinding,
  InputActionMap,
  InputActionSource,
  InputAxis,
  InputEvent,
  InputManagerConfig,
  InputManagerSnapshot,
  PointerState,
} from './input';
export {
  createInstancedMesh,
  generateInstanceData,
} from './instancing';
export type {
  BiomeData,
  InstanceData,
  InstancingOptions,
} from './instancing';
export {
  normalizeJoystick,
} from './joystick-normalize';
export type {
  JoystickVector,
  RawOffset,
} from './joystick-normalize';
export {
  batchLODObjects,
  calculateImpostorAngle,
  calculateLODLevel,
  calculateScreenSpaceSize,
  calculateVegetationDensity,
  createDitherPattern,
  createImpostorGeometry,
  createImpostorTexture,
  createLODLevels,
  createVegetationLODLevels,
  generateLODGeometries,
  interpolateLODMaterials,
  LODManager,
  shouldUseLOD,
  simplifyGeometry,
  updateImpostorUV,
} from './lod';
export type {
  ImpostorConfig,
  LODConfig,
  LODLevel,
  LODState,
  SimplificationOptions,
  VegetationLODConfig,
} from './lod';
export {
  createGeometryFromMarchingCubes,
  marchingCubes,
} from './marching-cubes';
export type {
  MarchingCubesOptions,
  MarchingCubesResult,
} from './marching-cubes';
export {
  approximately,
  buffer,
  clamp,
  clamp01,
  createNoise2D,
  createNoise3D,
  createNoise4D,
  createTerrainNoise,
  DEFAULT_FBM_CONFIG,
  degToRad,
  deltaAngle,
  distanceSquared2D,
  distanceSquared3D,
  easeInCubic,
  easeInOutCubic,
  easeOutCubic,
  easeOutElastic,
  easing,
  fbm2D,
  fbm3D,
  inverseLerp,
  lerp,
  lerpAngle,
  misc,
  moveTowards,
  pingPong,
  radToDeg,
  random,
  remap,
  remapRange,
  ridgedNoise2D,
  smoothDamp,
  smootherstep,
  smoothstep,
  TERRAIN_PRESETS,
  triangle,
  warpedNoise2D,
  warpedNoise3D,
  wrapAngle,
} from './math';
export type {
  EasingFn,
  FBMConfig,
  LerpFn,
  Noise2D,
  Noise3D,
  Noise4D,
  RandomFn,
  Range,
  TerrainNoisePreset,
  Vec2Like,
  Vec3Like,
  Vec4Like,
} from './math';
export {
  assertSolvable,
  buildCurvedWalls,
  buildGeometry,
  DEFAULT_CONFIG,
  distanceToWall,
  findDeadEnds,
  generateLayeredMaze,
  generateMaze,
  getConnections,
  getNodeConnections,
  gridToWorld,
  maxDeviation,
  minDistanceToWalls,
  worldToGrid,
} from './maze/index.js';
export type {
  BuildCurvedWallsOptions,
  CeilingTile,
  CurvedWall,
  DeadEnd,
  FloorTile,
  GenerateLayeredMazeOptions,
  LayerCellRef,
  LayerConnector,
  LayerConnectorKind,
  LayeredMaze,
  MazeCell,
  MazeConfig,
  MazeGeometry,
  MazeLayout,
  Passage,
  Point2,
  RailNode,
  SolvabilityReport,
  WallSegment,
  WobbleOptions,
} from './maze/index.js';
export {
  applyVariance,
  computeEmitPosition,
  computeEmitVelocity,
  createParticleEmitter,
  MAX_GRADIENT_STOPS,
  orientToDirection,
  ParticleEmitter,
  ParticleEmitterCore,
  particleFragmentShader,
  particleVertexShader,
  sampleShapePosition,
} from './particles';
export type {
  EmissionShape,
  EmitterShapeParams,
  ParticleBehavior,
  ParticleEmitterConfig,
  ParticleEmitterType,
  ParticleForces,
  RandomSource,
} from './particles';
export {
  addEdge,
  addNode,
  aGreedy,
  aStar,
  calculateDistance,
  createGraph,
  createGridGraph,
  createNGraph,
  createPathfinder,
  findClosestNode,
  findPath,
  findPathDijkstra,
  fromNavMesh,
  nba,
  simplifyPath,
  smoothPath,
} from './pathfinding';
export type {
  EdgeData,
  GraphEdge,
  GraphNode,
  NavMesh,
  NavMeshConversionOptions,
  NGraph,
  NLink,
  NNode,
  NodeData,
  NodeId,
  NPathFinder,
  PathfinderConfig,
  PathResult,
  Position3D,
  SmoothingOptions,
  StrataGraph,
  StrataGraphInstance,
  StrataPathfinderInstance,
  YukaVector3,
} from './pathfinding';
export {
  applyDrag,
  calculateBuoyancyForce,
  calculateExplosionForce,
  calculateForce,
  calculateImpulse,
  calculateJumpImpulse,
  calculateLandingVelocity,
  calculateSlopeAngle,
  calculateSteeringAngle,
  calculateSuspensionForce,
  collisionFilters,
  CollisionLayer,
  createDefaultBuoyancyConfig,
  createDefaultCharacterConfig,
  createDefaultDestructibleConfig,
  createDefaultPhysicsConfig,
  createDefaultVehicleConfig,
  createHumanoidRagdoll,
  generateDebrisVelocity,
  isWalkableSlope,
  projectVelocityOntoGround,
} from './physics';
export type {
  BuoyancyConfig,
  CharacterControllerConfig,
  CollisionFilter,
  DestructibleConfig,
  PhysicsConfig,
  PhysicsMaterial,
  RagdollBodyPart,
  RagdollConfig,
  RagdollJointConfig,
  VehicleConfig,
  WheelConfig,
} from './physics';
export {
  apertureToBokehScale,
  blendPostProcessingPresets,
  calculateFocusDistance,
  calculateFocusDistanceToMesh,
  defaultEffectSettings,
  dofScenarios,
  focalLengthToFOV,
  fovToFocalLength,
  getTimeOfDayEffects,
  lutConfigs,
} from './postProcessing';
export type {
  BloomSettings,
  BrightnessContrastSettings,
  ChromaticAberrationSettings,
  ColorGradingSettings,
  DOFSettings,
  FilmGrainSettings,
  LUTConfig,
  NoiseSettings,
  PostProcessingMood,
  PostProcessingPreset,
  SepiaSettings,
  SSAOSettings,
  ToneMappingSettings,
  VignetteSettings,
} from './postProcessing';
export {
  createRaymarchingGeometry,
  createRaymarchingMaterial,
} from './raymarching';
export type {
  RaymarchingMaterialOptions,
} from './raymarching';
export {
  getSafeAreaInsets,
  resetSafeAreaCache,
} from './safe-area-insets';
export type {
  SafeAreaInsets,
} from './safe-area-insets';
// Generic SDF primitives, operators, and legacy noise. Terrain-specific SDFs
// (sdTerrain, sdCaves, sdRock) and the biome height field come from './terrain'
// below. BiomeData is excluded here and exported via instancing, as before.
export {
  calcNormal,
  fbm,
  noise3D,
  opIntersection,
  opSmoothIntersection,
  opSmoothSubtraction,
  opSmoothUnion,
  opSubtraction,
  opUnion,
  sdBox,
  sdCapsule,
  sdCone,
  sdPlane,
  sdSphere,
  sdTorus,
  warpedFbm,
} from './sdf';
export {
  animationSnippet,
  buildFragmentShader,
  buildVertexShader,
  colorSnippet,
  composeShaderChunks,
  createColorUniform,
  createProgressUniform,
  createTimeUniform,
  createVector2Uniform,
  createVector3Uniform,
  lightingSnippet,
  noiseSnippet,
  ShaderChunks,
} from './shaders';
export type {
  AnimationChunk,
  ColorChunk,
  EffectsChunk,
  LightingChunk,
  NoiseChunk,
  ShaderChunkCategory,
  ShaderUniform,
  ShaderUniforms,
  UVChunk,
} from './shaders';
export {
  detectCapabilities,
  detectPlatform,
  isCapacitor,
  isNative,
  isReactNative,
  isWeb,
  resetPlatformCache,
  selectAdapter,
} from './shared';
export type {
  AdapterMap,
  Platform,
  PlatformCapabilities,
} from './shared';
export {
  createSkyGeometry,
  createSkyMaterial,
} from './sky';
export type {
  SkyMaterialOptions,
  TimeOfDayState,
  TimeOfDayStateCore,
  WeatherState,
  WeatherStateCore,
} from './sky';
export {
  calculateChecksum,
  create,
  createGameStore,
  createPersistenceAdapter,
  createWebPersistenceAdapter,
  immer,
  temporal,
  useStore,
  verifyChecksum,
  webPersistenceAdapter,
  WebPersistenceAdapter,
} from './state';
export type {
  AutoSaveConfig,
  CheckpointData,
  CheckpointOptions,
  GameStore,
  GameStoreActions,
  GameStoreApi,
  GameStoreState,
  PersistenceAdapter,
  SaveData,
  SaveInfo,
  StateChangeEvent,
  StateChangeType,
  StateListener,
  StoreConfig,
} from './state';
export type { TerrainChunk } from './terrain/index.js';
// Terrain generation. BiomeData is intentionally omitted — it reaches the
// barrel through './instancing' to avoid a duplicate-export conflict.
export {
  generateTerrainChunk,
  getBiomeAt,
  getTerrainHeight,
  sdCaves,
  sdRock,
  sdTerrain,
} from './terrain/index.js';
export {
  calculateFade,
  clampProgress,
  createDefaultCrosshair,
  createDefaultDamageNumber,
  createDefaultDialog,
  createDefaultInventory,
  createDefaultMinimap,
  createDefaultNameplate,
  createDefaultNotification,
  createDefaultProgressBar,
  createDefaultTooltip,
  formatNumber,
  formatProgressText,
  getAnchorOffset,
  getDamageNumberColor,
  getNotificationColor,
  getNotificationIcon,
  getTextDirection,
  screenToWorld,
  worldToScreen,
} from './ui';
export type {
  CrosshairConfig,
  DamageNumberConfig,
  DialogChoice,
  DialogConfig,
  DialogLine,
  InventoryConfig,
  InventorySlot,
  MinimapConfig,
  MinimapMarker,
  NameplateConfig,
  NotificationConfig,
  ProgressBarConfig,
  ScreenPosition,
  TextDirection,
  TooltipConfig,
  UIAnchor,
} from './ui';
export {
  createUnderwaterOverlayMaterial,
  createVolumetricFogMeshMaterial,
} from './volumetrics';
export type {
  UnderwaterOverlayMaterialOptions,
  VolumetricFogMeshMaterialOptions,
} from './volumetrics';
export {
  createAdvancedWaterMaterial,
  createWaterGeometry,
  createWaterMaterial,
} from './water';
export type {
  AdvancedWaterMaterialOptions,
  WaterMaterialOptions,
} from './water';
export {
  calculateTemperature,
  createWeatherSystem,
  createWindSimulation,
  getPrecipitationType,
  WeatherSystem,
  WeatherSystemCore,
  WindSimulation,
} from './weather';
export type {
  TemperatureConfig,
  WeatherStateConfig,
  WeatherSystemType,
  WeatherTransition,
  WeatherType,
  WindSimulationConfig,
} from './weather';
