import { defineConfig } from 'tsup';

const internalPackages = [
  '@strata-game-library/astro',
  '@strata-game-library/audio-synth',
  '@strata-game-library/capacitor',
  '@strata-game-library/core',
  '@strata-game-library/model-synth',
  '@strata-game-library/presets',
  '@strata-game-library/r3f',
  '@strata-game-library/react-native',
  '@strata-game-library/reactylon',
  '@strata-game-library/shaders',
];

const peerPackages = [
  '@babylonjs/core',
  '@react-three/drei',
  '@react-three/fiber',
  '@react-three/rapier',
  'astro',
  'postprocessing',
  'react',
  'react-dom',
  'react-native',
  'reactylon',
  'three',
  'tone',
  'typescript',
  'yuka',
  'zustand',
];

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    api: 'src/api.ts',
    components: 'src/components.ts',
    hooks: 'src/hooks.ts',
    core: 'src/core.ts',
    game: 'src/game.ts',
    compose: 'src/compose.ts',
    world: 'src/world.ts',
    utils: 'src/utils.ts',
    shaders: 'src/shaders.ts',
    presets: 'src/presets.ts',
    r3f: 'src/r3f.ts',
    reactylon: 'src/reactylon.ts',
    'audio-synth': 'src/audio-synth.ts',
    'model-synth': 'src/model-synth.ts',
    capacitor: 'src/capacitor.ts',
    'react-native': 'src/react-native.ts',
    astro: 'src/astro.ts',
  },
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  target: 'ES2022',
  treeshake: true,
  minify: false,
  keepNames: true,
  noExternal: internalPackages,
  external: peerPackages,
  banner: {
    js: '/* strata-game-library - umbrella ESM build */',
  },
});
